version: '3.9'

services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: buraksaglik_next_app

    restart: unless-stopped
    user: '1000:1000'

    environment:
      NODE_ENV: production
      PORT: 4000
      HOST: 0.0.0.0 # KRİTİK: Konteyner dışından (NPM'den) istek alabilmek için 0.0.0.0 olmalı!

    # AÇIKLAMA: NPM ile aynı Docker ağında olduğunuz için 'ports' bölümüne HİÇ GEREK YOKTUR.
    # Bu sayede 4000 portu sunucunun kendisine bile bağlanmaz, dış dünyaya %100 kapalı olur.
    # ports:
    #   - '127.0.0.1:4000:4000'

    read_only: true

    tmpfs:
      - /tmp
      - /app/.next/cache

    volumes:
      - ./logs:/app/logs

    security_opt:
      - no-new-privileges:true

    cap_drop: 
      - ALL

    networks:
      - app-network

networks:
  app-network:
    external: true
